### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl' and 'pwd'

### ISSUE THREAD

**Issue by a1023182899** [sml2h3/captcha_server#1]
it is wrong that ModuleNotFoundError: No module named 'fcntl' and 'pwd' when i execute 'gunicorn -c conf.py ocr_server:app'

my configuration is win10 , python 3.9

**Comment by sml2h3** [comment]
> it is wrong that ModuleNotFoundError: No module named 'fcntl' and 'pwd' when i execute 'gunicorn -c conf.py ocr_server:app'
> 
> my configuration is win10 , python 3.9

win10不用gunicorn，直接
`python ocr_server.py`
