### ISSUE TITLE
可以封装一个docker吗

### ISSUE THREAD

**Issue by luzihang123** [sml2h3/captcha_server#2]
尝试了多次，没有成功

**Comment by sml2h3** [comment]
可以，也可以等我做个pip包

**Comment by sml2h3** [comment]
> 尝试了多次，没有成功

为了方便大家使用,已将项目打包成pypi包
可以通过以下命令安装
pip install ddddocr==1.0.4

豆瓣源同步需要一些时间,目前建议通过官方源安装(命令后添加 -i https://pypi.org/simple)

使用方式为

import ddddocr

ocr = ddddocr.DdddOcr()

with open('test.png', 'rb') as f:
img_bytes = f.read()

res = ocr.classification(img_bytes)
print(res)
