### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by Arabot9** [sml2h3/captcha_server#4]
>pip install ddddocr==1.0.4
ERROR: Could not find a version that satisfies the requirement ddddocr==1.0.4 (from versions: none)
ERROR: No matching distribution found for ddddocr==1.0.4

**Comment by sml2h3** [comment]
python版本低啦，最低3.8
另外现在最新版已经1.0.6了

> > pip install ddddocr==1.0.4
> > ERROR: Could not find a version that satisfies the requirement ddddocr==1.0.4 (from versions: none)
> > ERROR: No matching distribution found for ddddocr==1.0.4
