### ISSUE TITLE
docker 启动无效

### ISSUE THREAD

**Issue by dashuaige2000** [sml2h3/captcha_server#5]
FROM python:3.8

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY . .

CMD ["gunicorn","ocr_server:app","-c","./conf.py"]

**Comment by Faner1990** [comment]
FROM python:3.8

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY . .

CMD ["gunicorn","ocr_server:app","-c","./conf.py"]

**Comment by sml2h3** [comment]
> FROM python:3.8
> 
> WORKDIR /usr/src/app
> 
> COPY requirements.txt ./
> 
> RUN pip install -r requirements.txt
> 
> COPY . .
> 
> CMD ["gunicorn","ocr_server:app","-c","./conf.py"]

可以尝试一下pypi版哈，docker我用的也不是很熟
